### ISSUE TITLE
Scan matcher: rely on odometry/velocity when ICP fails

### ISSUE THREAD

**Issue by corot** [CCNYRoboticsLab/scan_tools#20]
Hi, I use scan the matcher and I have sometimes errors like the following, mostly when the robot spins in place:

```
        : before trimming, only 25 correspondences.
icp: ICP failed for some reason. 
[ WARN] [1429886431.088875179, 47.800000000]: Error in scan matching
        : before trimming, only 15 correspondences.
icp: ICP failed for some reason. 
[ WARN] [1429886431.489196577, 48.200000000]: Error in scan matching
        : before trimming, only 13 correspondences.
icp: ICP failed for some reason. 
[ WARN] [1429886431.691738139, 48.400000000]: Error in scan matching
        : before trimming, only 13 correspondences.
icp: ICP failed for some reason. 
[ WARN] [1429886431.789825903, 48.500000000]: Error in scan matching
        : before trimming, only 19 correspondences.
icp: ICP failed for some reason. 
[ WARN] [1429886431.999484123, 48.700000000]: Error in scan matching
        : before trimming, only 10 correspondences.
icp: ICP failed for some reason. 
[ WARN] [1429886432.293471482, 49.000000000]: Error in scan matching
```

The effect is that the scan matcher pose jumps weirdly until the errors finish (last around 2 or 3 seconds) and then is not anymore attached to the robot. So I propose to changes:
- Rely on odometry or velocity inputs (if available) to update the pose when ICP fails
- Provide a "reset" service to restore the estimated pose to a given one (probably the current robot pose estimated by odom+localization)

**Comment by 130s** [comment]
Closing as https://github.com/CCNYRoboticsLab/scan_tools/pull/79 seems to be meant to address this. If it doesn't, please feel free to add more info.
